# Generated by Django 6.0.4 on 2026-05-28 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('score', models.FloatField(default=0.0)),
                ('ano', models.IntegerField(default=2024)),
                ('plat', models.CharField(default='PC', max_length=100)),
                ('imagem', models.CharField(blank=True, max_length=500)),
                ('destaque', models.BooleanField(default=False)),
                ('preco_steam', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('preco_nuuvem', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('preco_epic', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['-destaque', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
